# Directory containing model checkpoints.
CHECKPOINT_DIR="im2txt/model/train_RMSProp"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="im2txt/data/flickr8k/word_counts.txt"
A="im2txt/data/"

export JAVA_HOME=/opt/java/jdk1.8.0_51/
export JAVA_VERSION=1.8
BAZEL_PATH=~/bin/bazel/output/bazel
while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "Text read from file: $line"
    # JPEG image file to caption.

        IMAGE_FILE=$A$line

        # Build the inference binary.
        ${BAZEL_PATH} build -c opt im2txt/run_inference

        # Ignore GPU devices (only necessary if your GPU is currently memory
        # constrained, for example, by running the training script).
        # export CUDA_VISIBLE_DEVICES=""

        # Run inference to generate captions.
        bazel-bin/im2txt/run_inference \
          --checkpoint_path=${CHECKPOINT_DIR} \
          --vocab_file=${VOCAB_FILE} \
          --input_files=${IMAGE_FILE}
done < "$1"
